/-
  Restricted Burnside Problem Generalizations

  Domain: mathematics
  ID: opa.mathematics.combinatorics.burnside-problem-bounded-exponent
  Status: Open

  Consider a group generated by d elements where every element raised to the n-th power equals the identity. Is this group always finite? The answer is no for large n, and yes for small n, but the exact dividing line is unknown.

-/

-- This is a formalization stub. The actual proof is an open problem.
-- See: https://openproblem-atlas.org/problem/opa-mathematics-combinatorics-burnside-problem-bounded-exponent.html

/-- Restricted Burnside Problem Generalizations -/
axiom RestrictedBurnsideProblemGeneralizations : True  -- OPEN PROBLEM: formal statement needed
