"""Frankl's union-closed sets conjecture checker (specific bounds).

For every finite union-closed family F (not all empty), some element
appears in at least |F|/2 sets. This checker exhaustively tests all
union-closed families generated by subsets of {1,...,n}.
"""

from itertools import combinations


def verify(params: dict) -> dict:
    max_n = int(params.get("max_n", 8))
    max_n = min(max_n, 12)
    # For feasibility, limit actual exhaustive search
    actual_n = min(max_n, 5)

    total_checked = 0
    min_ratio = 1.0
    worst_family_size = 0

    for n in range(1, actual_n + 1):
        ground = list(range(1, n + 1))
        all_subsets = []
        for r in range(n + 1):
            for c in combinations(ground, r):
                all_subsets.append(frozenset(c))

        # Generate union-closed families from pairs of generating sets
        for g1, g2 in combinations(all_subsets, 2):
            if len(g1) == 0 and len(g2) == 0:
                continue
            family = {frozenset(), g1, g2, g1 | g2}
            changed = True
            while changed:
                changed = False
                new = set()
                for a in family:
                    for b in family:
                        u = a | b
                        if u not in family:
                            new.add(u)
                            changed = True
                family |= new

            non_empty = [s for s in family if len(s) > 0]
            if not non_empty:
                continue

            total_checked += 1
            universe = set()
            for s in non_empty:
                universe |= s

            best_freq = 0
            for elem in universe:
                freq = sum(1 for s in family if elem in s)
                if freq > best_freq:
                    best_freq = freq

            ratio = best_freq / len(family)
            if ratio < min_ratio:
                min_ratio = ratio
                worst_family_size = len(family)

            if best_freq < len(family) / 2:
                return {
                    "status": "fail",
                    "summary": f"Frankl violated: best element frequency {best_freq}/{len(family)}",
                    "details": {"family_size": len(family), "ground_set": n},
                }

    return {
        "status": "pass",
        "summary": (
            f"Frankl's conjecture verified for {total_checked} union-closed families "
            f"on ground sets up to {actual_n}. Min element ratio: {min_ratio:.4f}"
        ),
        "details": {
            "max_n": actual_n,
            "total_checked": total_checked,
            "min_ratio": round(min_ratio, 4),
            "worst_family_size": worst_family_size,
        },
    }


if __name__ == "__main__":
    import json
    print(json.dumps(verify({}), indent=2))
