"""Frankl's conjecture (union-closed sets) checker.

Frankl's conjecture: for every finite union-closed family of finite sets
(not consisting only of the empty set), there exists an element that
belongs to at least half of the sets in the family.
Verifies by exhaustive check for all union-closed families on ground set {1,...,n}.
"""

from itertools import combinations


def _is_union_closed(family: list[frozenset]) -> bool:
    """Check if a family of sets is union-closed."""
    family_set = set(family)
    for a in family:
        for b in family:
            if a | b not in family_set:
                return False
    return True


def _check_frankl(family: list[frozenset]) -> bool:
    """Check if Frankl's conjecture holds for this family."""
    if not family or all(len(s) == 0 for s in family):
        return True  # trivial / empty

    universe = set()
    for s in family:
        universe |= s

    n = len(family)
    for elem in universe:
        count = sum(1 for s in family if elem in s)
        if count >= n / 2:
            return True
    return False


def verify(params: dict) -> dict:
    max_ground_set = int(params.get("max_ground_set", 5))
    # Limit ground set size for feasibility
    max_ground_set = min(max_ground_set, 6)

    total_checked = 0
    violations = []

    for n in range(1, max_ground_set + 1):
        ground = list(range(1, n + 1))
        all_subsets = [frozenset()]
        for r in range(1, n + 1):
            for c in combinations(ground, r):
                all_subsets.append(frozenset(c))

        # Generate union-closed families by taking closure of small generating sets
        # For efficiency, only check families generated by 2-3 sets
        for gen_size in range(1, min(4, len(all_subsets))):
            for generators in combinations(all_subsets, gen_size):
                if all(len(g) == 0 for g in generators):
                    continue

                # Generate union closure
                family = set(generators)
                family.add(frozenset())  # empty set is often included
                changed = True
                while changed:
                    changed = False
                    new = set()
                    for a in family:
                        for b in family:
                            u = a | b
                            if u not in family:
                                new.add(u)
                                changed = True
                    family |= new

                family_list = sorted(family, key=lambda s: (len(s), sorted(s)))

                if len(family_list) < 2:
                    continue

                total_checked += 1
                if not _check_frankl(family_list):
                    violations.append({
                        "ground_set_size": n,
                        "family_size": len(family_list),
                    })

    if violations:
        return {
            "status": "fail",
            "summary": f"Frankl's conjecture violated for {len(violations)} families",
            "details": {"violations": violations[:10]},
        }

    return {
        "status": "pass",
        "summary": (
            f"Frankl's conjecture verified for {total_checked} union-closed families "
            f"on ground sets up to size {max_ground_set}"
        ),
        "details": {"max_ground_set": max_ground_set, "total_checked": total_checked},
    }


if __name__ == "__main__":
    import json
    print(json.dumps(verify({"max_ground_set": 4}), indent=2))
