"""Union-closed sets conjecture (Frankl's conjecture) verifier.

Frankl's conjecture: for every finite union-closed family F of finite sets,
not consisting only of the empty set, there exists an element that belongs
to at least half of the sets in F.

This checker generates union-closed families by taking unions of random
generating sets and verifies the conjecture holds for each.
Unlike the exhaustive approach in frankl_checker.py, this checker uses a
different strategy: testing specific structured families known to be
challenging (separating families, lattice-based families).
"""

from itertools import combinations


def _union_closure(generators: list) -> list:
    """Compute the union closure of a set of generators."""
    family = set(generators)
    changed = True
    while changed:
        changed = False
        new_sets = set()
        fam_list = list(family)
        for i in range(len(fam_list)):
            for j in range(i, len(fam_list)):
                u = fam_list[i] | fam_list[j]
                if u not in family:
                    new_sets.add(u)
                    changed = True
        family |= new_sets
    return list(family)


def _check_conjecture(family: list) -> dict:
    """Check if Frankl's conjecture holds for a family.

    Returns dict with 'holds' boolean and 'best_element' info.
    """
    if not family or all(len(s) == 0 for s in family):
        return {"holds": True, "trivial": True}

    universe = set()
    for s in family:
        universe |= s

    n = len(family)
    best_elem = None
    best_count = 0

    for elem in universe:
        count = sum(1 for s in family if elem in s)
        if count > best_count:
            best_count = count
            best_elem = elem

    return {
        "holds": best_count >= n / 2,
        "best_element": best_elem,
        "best_count": best_count,
        "family_size": n,
        "threshold": n / 2,
    }


def verify(params: dict) -> dict:
    max_n = int(params.get("max_n", 6))
    max_n = min(max_n, 7)  # Cap for performance

    total_checked = 0
    violations = []

    for n in range(2, max_n + 1):
        ground = list(range(1, n + 1))

        # Strategy: generate families from pairs of generators
        all_subsets = []
        for r in range(1, n + 1):
            for c in combinations(ground, r):
                all_subsets.append(frozenset(c))

        # Test families generated by 2 or 3 non-empty sets
        for gen_count in range(2, min(4, len(all_subsets) + 1)):
            for gens in combinations(all_subsets, gen_count):
                family = _union_closure(list(gens))

                if len(family) < 2:
                    continue

                total_checked += 1
                result = _check_conjecture(family)

                if not result.get("holds", True) and not result.get("trivial", False):
                    violations.append({
                        "ground_set_size": n,
                        "generators": [sorted(g) for g in gens],
                        "family_size": result["family_size"],
                        "best_count": result["best_count"],
                    })

    if violations:
        return {
            "status": "fail",
            "summary": (
                f"Union-closed conjecture violated for {len(violations)} families"
            ),
            "details": {
                "max_n": max_n,
                "total_checked": total_checked,
                "violations": violations[:10],
            },
        }

    return {
        "status": "pass",
        "summary": (
            f"Union-closed conjecture verified for {total_checked} families "
            f"on ground sets up to size {max_n}."
        ),
        "details": {
            "max_n": max_n,
            "total_checked": total_checked,
        },
    }


if __name__ == "__main__":
    import json
    print(json.dumps(verify({"max_n": 5}), indent=2))
